name: Android CI (Local Build)

# Trigger on pushes to develop or any feature branch, and on PRs targeting develop
on:
  push:
    branches:
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - develop

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install your JS dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Kill any leftover Gradle daemons (clean build)
      - name: Kill Gradle daemons
        run: |
          cd android
          ./gradlew --stop
          cd ..

      # 5. Wipe out the Gradle cache for a truly fresh build
      - name: Clear Gradle cache
        run: rm -rf ~/.gradle/caches

      # 6. Generate/update the native Android project via Expo
      - name: Expo prebuild (android, clean)
        run: npx expo prebuild --platform android --clean

      # 7. Install Java (JDK 17—fully compatible with your Gradle plugin)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 8. Install the Android SDK exactly matching your compileSdk/buildTools/NDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35             # compileSdkVersion from your logs
          build-tools: '35.0.0'     # buildToolsVersion
          ndk: '27.1.12297006'      # ndkVersion
          cmake: false

      # 9. Run Gradle to assemble a debug APK
      - name: Assemble Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon
          cd ..

      # 10. Publish the resulting APK as an artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
