services:
  # Service de base de données SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=@Ega1234
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 15s

  # Service d'analyse antivirus ClamAV
  clamav:
    image: clamav/clamav:1.3
    container_name: clamav-dev
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clamdb:/var/lib/clamav

  # Service pour l'API de Lookup (lecture seule)
  lookup-api:
    build: ./app-backend
    container_name: lookup-api-dev
    command: npm run dev:lookup
    env_file:
      - ./.env # Chemin mis à jour vers la racine
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - ./app-backend:/app
      - /app/node_modules

  # Service pour l'API Transactionnelle (écriture)
  trx-api:
    build: ./app-backend
    container_name: trx-api-dev
    command: npm run dev:trx
    env_file:
      - ./.env # Chemin mis à jour vers la racine
    depends_on:
      db:
        condition: service_healthy
      clamav:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - ./app-backend:/app
      - /app/node_modules
      - ./app-backend/uploads:/app/uploads

volumes:
  mssql_data:
  clamdb: