version: "3.9"

services:
  # ── (Optional) Local SQL Server on the VM ──
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=${DB_SA_PASSWORD}
    # Don't expose to the internet
    # If you need host access for debugging, bind to localhost only:
    # ports:
    #   - "127.0.0.1:1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 15s
    restart: unless-stopped

  # ── ClamAV for file scanning ──
  clamav:
    image: clamav/clamav:1.3
    restart: unless-stopped
    volumes:
      - clamdb:/var/lib/clamav
    # No need to publish 3310 unless scanning from outside

  # ── Lookup API (internal) ──
  lookup-api:
    build:
      context: ./app-backend
      dockerfile: Dockerfile.vm
    command: npm run dev:lookup     # or "npm run start:lookup" if you have it
    environment:
      - DATABASE_URL=sqlserver://db:1433;database=ComplaintDev;user=${DB_LOOKUP_USER};password=${DB_LOOKUP_PASSWORD};trustServerCertificate=true;encrypt=false
      - PORT=3001
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    # keep internal; no published ports
    restart: unless-stopped

  # ── TRX API (public) ──
  trx-api:
    build:
      context: ./app-backend
      dockerfile: Dockerfile.vm
    command: npm run dev:trx         # or "npm run start:trx"
    environment:
      - DATABASE_URL=sqlserver://db:1433;database=ComplaintDev;user=${DB_SERVICE_USER};password=${DB_SERVICE_PASSWORD};trustServerCertificate=true;encrypt=false
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
      clamav:
        condition: service_started
    ports:
      - "80:3000"                    # reachable at http://<VM-IP>
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  mssql_data: {}
  clamdb: {}
  uploads: {}
