services:
  # Service de base de données SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=@Ega1234
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 15s

  # Service d'analyse antivirus ClamAV
  clamav:
    image: clamav/clamav:1.3
    container_name: clamav-dev
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clamdb:/var/lib/clamav

  # Service de notre API Backend
  api:
    build: ./app-backend
    container_name: complaint-api-dev
    ports:
      - "3001:3000"
    volumes:
      - ./app-backend:/app
      - /app/node_modules
    env_file:
      - ./app-backend/.env
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
      clamav:
        condition: service_started

volumes:
  mssql_data:
  clamdb: