services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=${DB_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 15s

  clamav:
    image: clamav/clamav:1.3
    container_name: clamav-dev
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clamdb:/var/lib/clamav

  lookup-api:
    build: ./app-backend
    container_name: lookup-api-dev
    command: npm run dev:lookup
    environment:
      - DATABASE_URL=sqlserver://db:1433;database=ComplaintDev;user=${DB_LOOKUP_USER};password=${DB_LOOKUP_PASSWORD};trustServerCertificate=true;encrypt=false
      - PORT=${LOOKUP_API_PORT}
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - ./app-backend:/app
      - /app/node_modules

  trx-api:
    build: ./app-backend
    container_name: trx-api-dev
    command: npm run dev:trx
    environment:
      - DATABASE_URL=sqlserver://db:1433;database=ComplaintDev;user=${DB_SERVICE_USER};password=${DB_SERVICE_PASSWORD};trustServerCertificate=true;encrypt=false
      - CLAMAV_HOST=${CLAMAV_HOST}
      - CLAMAV_PORT=${CLAMAV_PORT}
      - PORT=${TRX_API_PORT}
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
      clamav:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - ./app-backend:/app
      - /app/node_modules
      - ./app-backend/uploads:/app/uploads

volumes:
  mssql_data: {}
  clamdb: {}