name: Android CI (Local Build)

on:
  push:
    branches:
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - develop

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Kill Gradle daemons
        run: |
          cd android
          ./gradlew --stop
          cd ..

      - name: Clear Gradle cache
        run: rm -rf ~/.gradle/caches

      - name: Expo prebuild (android, clean)
        run: npx expo prebuild --platform android --clean

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: '35.0.0'
          ndk: '27.1.12297006'
          cmake: false

      - name: Assemble Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon
          cd ..

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4       # ← updated to v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
